//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagentoStoreUpdateByAPI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class MagentoStoreUpdate : global::System.Configuration.ApplicationSettingsBase {
        
        private static MagentoStoreUpdate defaultInstance = ((MagentoStoreUpdate)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MagentoStoreUpdate())));
        
        public static MagentoStoreUpdate Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ewright@shoesensation.com")]
        public string ErrorEmail {
            get {
                return ((string)(this["ErrorEmail"]));
            }
            set {
                this["ErrorEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompareAndCreate {
            get {
                return ((bool)(this["CompareAndCreate"]));
            }
            set {
                this["CompareAndCreate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateStoreInfo {
            get {
                return ((bool)(this["UpdateStoreInfo"]));
            }
            set {
                this["UpdateStoreInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateStoreDesc {
            get {
                return ((bool)(this["UpdateStoreDesc"]));
            }
            set {
                this["UpdateStoreDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportStoreInfo {
            get {
                return ((bool)(this["ImportStoreInfo"]));
            }
            set {
                this["ImportStoreInfo"] = value;
            }
        }
    }
}
