//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeBuck_Sender {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ShoeBuck_Sender : global::System.Configuration.ApplicationSettingsBase {
        
        private static ShoeBuck_Sender defaultInstance = ((ShoeBuck_Sender)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ShoeBuck_Sender())));
        
        public static ShoeBuck_Sender Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ewright@shoesensation.com, cbrehm@shoesensation.com")]
        public string EmailError {
            get {
                return ((string)(this["EmailError"]));
            }
            set {
                this["EmailError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7Slf0amc0sSiST8q1lFuP9TzaWaa2oa04bzaBbUH")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
    }
}
